// ems_params_pkg.sv -- GENERATED by hw/scripts/export_model.py. Do not edit.
// Source model: FinalModels/FourConnModel/conn_stacking_ensemble.joblib
// Families (stream order): erp=104, bp=300, tf=1200, conn=60
package ems_params_pkg;
  localparam int N_FEAT = 1664;
  localparam int N_FAM  = 4;
  // index of the LAST feature of each family, in stream order
  localparam int FAM_END [N_FAM] = '{103, 403, 1603, 1663};

  // Default (power-on) values; all are overwritable over the cfg port.
  // Family LDA biases, Q.16, [family][class]
  localparam logic signed [31:0] BIAS_INIT [N_FAM][3] = '{
    '{-32'sd126641, -32'sd48049, -32'sd132842},
    '{-32'sd138968, -32'sd50925, -32'sd162649},
    '{-32'sd151767, -32'sd57826, -32'sd170243},
    '{-32'sd105993, -32'sd46444, -32'sd105493}
  };
  // Meta-learner coefficients, Q2.15, [class][family*3 + family_class]
  localparam logic signed [17:0] MC_INIT [3][12] = '{
    '{18'sd59750, -18'sd28623, -18'sd34602, 18'sd53627, 18'sd28, -18'sd57130, 18'sd14107, -18'sd3601, -18'sd13981, 18'sd58073, -18'sd9562, -18'sd51987},
    '{-18'sd5026, 18'sd21716, -18'sd7977, 18'sd495, 18'sd6451, 18'sd1767, 18'sd648, 18'sd8000, 18'sd65, -18'sd7097, 18'sd9063, 18'sd6747},
    '{-18'sd54724, 18'sd6907, 18'sd42579, -18'sd54121, -18'sd6479, 18'sd55363, -18'sd14755, -18'sd4399, 18'sd13916, -18'sd50976, 18'sd498, 18'sd45240}
  };
  // Meta-learner intercepts, Q.16
  localparam logic signed [31:0] MB_INIT [3] = '{-32'sd7877, 32'sd19480, -32'sd11603};
endpackage
