"""
export_model.py
===============
FourConnModel joblib -> FPGA memory images + generated SystemVerilog package.

Writes:
  hw/rtl/mem/weights.mem      1664 x 54-bit  {w2,w1,w0} folded LDA weights (Q1.16)
  hw/rtl/mem/exp_lut.mem      1024 x 18-bit  2^(-i/1024) (Q1.17)
  hw/rtl/ems_params_pkg.sv    feature counts, family boundaries, default biases
                              and meta-learner coefficients (register reset values)

Run from anywhere:
    python hw/scripts/export_model.py
"""
from __future__ import annotations
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common as c
import fxp


def _hex(v, bits):
    return f"{int(v) & ((1 << bits) - 1):0{(bits + 3) // 4}x}"


def _sv_signed(v, bits):
    v = int(v)
    return f"-{bits}'sd{-v}" if v < 0 else f"{bits}'sd{v}"


def write_mems(qm, out_dir=c.MEM_DIR):
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "weights.mem"), "w") as f:
        f.writelines(_hex(w, 54) + "\n" for w in fxp.weight_words(qm))
    with open(os.path.join(out_dir, "exp_lut.mem"), "w") as f:
        f.writelines(_hex(v, fxp.E_BITS) + "\n" for v in fxp.EXP_LUT)


def write_pkg(qm, dims, path=os.path.join(c.HW_DIR, "rtl", "ems_params_pkg.sv")):
    ends, acc = [], 0
    for d in dims:
        acc += d; ends.append(acc - 1)
    bias = ",\n    ".join(
        "'{" + ", ".join(_sv_signed(qm["b"][f][j], 32) for j in range(3)) + "}"
        for f in fxp.FAMILIES)
    mc = ",\n    ".join(
        "'{" + ", ".join(_sv_signed(qm["mc"][j, i], 18) for i in range(12)) + "}"
        for j in range(3))
    mb = ", ".join(_sv_signed(qm["mb"][j], 32) for j in range(3))
    src = f"""// ems_params_pkg.sv -- GENERATED by hw/scripts/export_model.py. Do not edit.
// Source model: FinalModels/FourConnModel/conn_stacking_ensemble.joblib
// Families (stream order): {', '.join(f'{f}={d}' for f, d in zip(fxp.FAMILIES, dims))}
package ems_params_pkg;
  localparam int N_FEAT = {sum(dims)};
  localparam int N_FAM  = {len(dims)};
  // index of the LAST feature of each family, in stream order
  localparam int FAM_END [N_FAM] = '{{{', '.join(map(str, ends))}}};

  // Default (power-on) values; all are overwritable over the cfg port.
  // Family LDA biases, Q.16, [family][class]
  localparam logic signed [31:0] BIAS_INIT [N_FAM][3] = '{{
    {bias}
  }};
  // Meta-learner coefficients, Q2.15, [class][family*3 + family_class]
  localparam logic signed [17:0] MC_INIT [3][12] = '{{
    {mc}
  }};
  // Meta-learner intercepts, Q.16
  localparam logic signed [31:0] MB_INIT [3] = '{{{mb}}};
endpackage
"""
    with open(path, "w") as f:
        f.write(src)


def main():
    art = c.load_model()
    fm = fxp.fold_model(art)
    qm = fxp.quantize_model(fm)
    dims = [qm["W"][f].shape[1] for f in fxp.FAMILIES]
    write_mems(qm)
    write_pkg(qm, dims)
    print(f"exported {sum(dims)} features {dims} -> {c.MEM_DIR} + ems_params_pkg.sv")
    return qm


if __name__ == "__main__":
    main()
